language: node_js
node_js:
  - 'v14.15.4'
install: yarn install
services:
  - mysql
  - redis-server
before_script:
  - cp .env.example .env
  - mkdir storage/sessions
  - mkdir storage/logs
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;'
script: yarn test