language: node_js
node_js:
  - 'v12.20.0'
install: yarn install
services:
  - mysql
before_script:
  - cp .env.example .env
  - mkdir storage/sessions
  - mkdir storage/logs
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;'
script: yarn test
after_success: yarn run coverage